# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58db30d72d30ef47393b7c430c111bc1ab82b998ccdbc10248c832aa915af643f9f6a0c455b2e42e215b529dd3939f1b3fbeccd1adcd31575443c8e2ce02f78b

test:
  secret_key_base: b2e4c6322a2aafea7ae948460a4c4e2ec576caf826e8e28f0b3d9d0e42b49122463252a96db0a144d81cf5798754116f1a07539bf7853457e7017dddbae0470e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
